[build.env]
passthrough = [
    "RUSTFLAGS",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture amd64",
    "apt-get update",
    "apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update", 
    "apt-get install -y libwebkit2gtk-4.0-dev:arm64 libgtk-3-dev:arm64 libayatana-appindicator3-dev:arm64 librsvg2-dev:arm64 build-essential curl wget libssl-dev:arm64 gcc-aarch64-linux-gnu"
]
